# Generated by Django 5.2.8 on 2025-11-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('merchant', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
